### ISSUE TITLE
@serverless-stack/cli - TypeError: getAwsCredentials is not a function after V1 migration

### ISSUE THREAD

**Issue by klindklind** [serverless-stack/serverless-stack#1610]
Improvements you've done for the V1 api is really moving the framework forward even though I've been enjoying using the 0.x version as well 👍 

I'm using TypeScript and I did try to upgrade from 0.69.5 -> 1.0.0-beta.5 using these instructions [](https://docs.serverless-stack.com/constructs/migration#upgrade-steps) to get head start to V1.

The upgrade + following stack definitions type fixes went smoothly

```
Updating @serverless-stack/cli to 1.0.0-beta.5
Updating @serverless-stack/resources to 1.0.0-beta.5
Updating aws-cdk-lib@2.15.0
Updating @aws-cdk/aws-appsync-alpha@2.15.0-alpha.0
SST: 1.0.0-next.29+36881bd2
CDK: 2.15.0

```

However the `npx sst *` commands won't work anymore. I've tried both AWS_PROFILE+`~/.aws/credentials` (works fine with SST 0.69.5) and `AWS_ACCESS_KEY_ID` + `AWS_SECRET_ACCESS_KEY` + `AWS_SESSION_TOKEN` but I keep getting

```
npx sst build

TypeError: getAwsCredentials is not a function
    at loadAwsCredentials (****/node_modules/@serverless-stack/cli/bin/scripts.js:232:29)
    at run (****/node_modules/@serverless-stack/cli/bin/scripts.js:514:9)

```

Using aws-cli version `2.5.3`

Is anyone else experiencing this?

**Comment by ibraelillo** [comment]
me too

**Comment by fwang** [comment]
@klindklind the log u shared shows SST upgraded to `1.0.0-next.29+36881bd2`, which looked weird.

@klindklind @ibraelillo Could you check the version for `@serverless-stack/cli` and `@serverless-stack/core` in your package.json after grading?

**Comment by fwang** [comment]
@JDanielGalvan does the error show after the stacks are successfully deployed? can you share a screenshot of the error?

**Comment by ddaversa** [comment]
I second, I have the same exact problem.

in scripts.js,

```
const {
  logger,
  initializeLogger,
  Packager,
  Update,
  State,
  Telemetry,
  getCdkVersion,
  getAwsCredentials,
} = require("@serverless-stack/core");
```

... does not seem to exist in that file.

**Comment by fwang** [comment]
@ddaversa what are the versions for @serverless-stack/cli and @serverless-stack/core in your package.json?

**Comment by ddaversa** [comment]
> @ddaversa what are the versions for @serverless-stack/cli and @serverless-stack/core in your package.json?

Sorry, edited my message around the same time you posted;

package.json contents

[...]
"dependencies": {
   "@serverless-stack/cli": "1.0.0-beta.5",
    "@serverless-stack/resources": "1.0.0-beta.5",
    "aws-cdk-lib": "2.15.0",
[...]
Should /core be in there ?

**Comment by fwang** [comment]
I see. `core` is a dependency of `cli` and `resources`.

Can you go into `node_modules/@serverless-stack/cli/package.json` and see what version of `core` it is depending on?

**Comment by ddaversa** [comment]
> I see. `core` is a dependency of `cli` and `resources`.
> 
> Can you go into `node_modules/@serverless-stack/cli/package.json` and see what version of `core` it is depending on?



That would be
```
"@serverless-stack/core": "^1.0.0-beta.5",
```

I've manually added it back to package.json, and the error is gone! Maybe the upgrade removed the dependency? Strange.

**Comment by fwang** [comment]
>I've manually added it back to package.json, and the error is gone! Maybe the upgrade removed the dependency? Strange.

Do u mean u manually added it back to the root package.json?

**Comment by ddaversa** [comment]
> > I've manually added it back to package.json, and the error is gone! Maybe the upgrade removed the dependency? Strange.
> 
> Do u mean u manually added it back to the root package.json?

Yes, that is correct. Doing so fixed it for me (though that's not a proper fix, I know)

**Comment by fwang** [comment]
Thanks @ddaversa. I think I've found the issue. It seems updating to `1.0.0-beta.5` ended up installing two `@serverless-stack/core` in node_modules, one with `1.0.0.beta.5` and one with `1.0.0-next.29`.

Not sure why yet.. looking into it.

**Comment by JDanielGalvan** [comment]
> 
@fwang 

![sst_1](https://user-images.githubusercontent.com/5453896/162502805-f553a87d-f549-4369-970f-50f013756309.png)

![sst_2](https://user-images.githubusercontent.com/5453896/162502843-c96ef92d-ecf4-47d1-ac0a-db3618ed791c.png)

**Comment by fwang** [comment]
Thanks @JDanielGalvan!

Can u check the version for @serverless-stack/cli and @serverless-stack/core in your package.json?

**Comment by fwang** [comment]
@klindklind @ibraelillo @ddaversa This should be fixed in `v1.0.0-beta.9`, give it a try!

**Comment by JDanielGalvan** [comment]
> Thanks @JDanielGalvan!
> 
> Can u check the version for @serverless-stack/cli and @serverless-stack/core in your package.json?

@fwang The "serverless-stack" dependencies in the package.son are the following:

"@serverless-stack/cli": "0.69.5",
"@serverless-stack/resources": "0.69.5",

**Comment by klindklind** [comment]
Thanks a Lot @fwang for quick response! I'll try that version you pointed out and let you know how it went 🙏

**Comment by klindklind** [comment]
Works as a charm in 1.0.0-beta.9 🎉  Closing this.
